.\"                                      Hey, EMACS: -*- nroff -*-
.TH SJENG 6 "May 28, 2002"
.SH NAME
sjeng \- Chess program which supports several variants
.SH SYNOPSIS
.B sjeng
.SH DESCRIPTION
Documentation for sjeng is available in /usr/share/doc/sjeng*/README.
It is strongly recommended that you use sjeng in combination with some
interface like xboard or eboard. Please read the documentation of
xboard and eboard to find out how to use other chess engines.
.PP
There are no command line options for sjeng, but sjeng uses a
configuration file, by default /etc/sjeng.rc. If present, the file
~/.sjeng/sjeng.rc in the user's home directory will be read instead of
the system default. A well-documented example configuration can be
found in /usr/share/doc/sjeng*/examples/.
.PP
This manual page was written for the Debian distribution because the
original program does not have a manual page, and was also adopted by
Mandriva package.
.SH AUTHOR
Sjeng was written by Gian-Carlo Pascutto <gcp@sjeng.org>, based on
work done by Adrien Regimbald <adrien@gpu.srv.ualberta.ca>.
.PP
This manual page was written by Lukas Geyer
<lukas@debian.org>, for the Debian GNU/Linux system (but may
be used by others).
